name: progress_tab_bar
description: A flutter package which implements a tab bar for displaying sub-steps of a process in a sequence.
version: 0.1.7
repository: https://github.com/underwhelmingToaster/progress_tab_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
